### ISSUE TITLE
[2022] Grupos

### ISSUE THREAD

**Issue by jemaf** [COLTEC-DAW/TP-01-HTML-SCSS-RWD#36]
Inscreva seu grupo para apresentação aqui.
Para isso, utilize o seguinte modelo:

* Integrantes: João, Maria, José, Ana
* Sistema clonado: GitHub (páginas principal e repositório)

**Comment by ViolanteGabriel** [comment]
- Integrantes: Gabriel Machado Violante, Gabriel Benvindo Begnami, Éric Catarina Parreiras, Arthur Cordeiro Ferreira Souza.
- Sistema clonado: Netflix (site de streaming de filmes e séries).

**Comment by Aikenpil** [comment]
Integrantes: Gustavo Rangel, Jean Berly, Gabriel Moreira, Daniel de Miranda.
Sistema clonado: Coltec (main page e do curso de info).

**Comment by ambueno** [comment]
- Integrantes: Amanda Bueno, Bernardo Vale;
- Sistema clonado: Tesla (Roadster e Model S);

**Comment by ThiagoL29** [comment]
- Integrantes: Thiago, Gustavo Augusto, Pedro e Eduardo;
- Sistema clonado: Google Meet (Página inicial e reunião)

**Comment by fernandrade04** [comment]
Integrantes: João Victor, Fernando, Elder Gabriel
Sistema clonado: Facebook

**Comment by GabrielR03** [comment]
Integrantes: Gabriel Rodrigues, Bernardo Tavares, Guilherme Diniz e Lorrayne Soares;
Sistema clonado: Spotify main page e sign-in;
